- id: nb-ensure-clean
  name: nb-ensure-clean
  description: Ensure that committed Jupyter notebooks contain no outputs.
  entry: nb-ensure-clean
  files: \.ipynb$
  language: python
  language_version: python3
